= Hardware & Edge Computing (ESP32-C3)

The edge layer of QuakeGuard is designed to operate on resource-constrained microcontrollers, specifically targeting the ESP32-C3 SuperMini platform (RISC-V architecture). The node interfaces with an ADXL345 digital accelerometer to acquire, filter, and analyze seismic data locally, transmitting only cryptographically signed anomaly reports to conserve bandwidth.

== Hardware Configuration & Interfacing

Due to the specific physical layout of the ESP32-C3 SuperMini, the I2C bus is software-mapped to non-standard GPIO pins:
- *SDA (Data):* Mapped to GPIO 7, requiring internal pull-up resistors.
- *SCL (Clock):* Mapped to GPIO 8, requiring internal pull-up resistors.
- *Power Constraints:* The ADXL345 is powered strictly via the 3.3V rail; applying 5V will result in immediate hardware damage.

The sensor operates at a 100Hz sampling rate (`ADXL345_DATARATE_100_HZ`) with a measurement range of $plus.minus 16 G$ (`ADXL345_RANGE_16_G`). To prevent I2C bus race conditions during startup, the sensor object is instantiated dynamically in memory only after the hardware bus is fully stabilized.

== Digital Signal Processing (DSP) & Calibration Pipeline

Raw acceleration data undergoes multiple stages of local processing and calibration before being evaluated:
- *Static Offset Calibration:* Upon boot, the sensor performs a static 100-sample averaging sequence while the node is at rest. The calculated positional offsets are written directly to the ADXL345 hardware registers (`OFSX`, `OFSY`, `OFSZ`), inherently zeroing the sensor at the hardware level and removing physical mounting biases.
- *High-Pass Filter (HPF):* A digital filter (`HPF_ALPHA = 0.9f`) isolates the dynamic vibration data by subtracting the static DC component (Earth's gravity, approx. 9.81 $m/s^2$).
- *Noise Gate:* Micro-vibrations below the empirical threshold of 0.04G are clamped to zero to prevent false positives generated by electrical noise.
- *Dropout Protection:* The firmware automatically drops frames reporting near-zero absolute acceleration (less than 2.0 $m/s^2$ prior to filtering), effectively mitigating corrupted readings caused by temporary I2C wire disconnects.

== STA/LTA Seismic Detection Algorithm

QuakeGuard implements the industry-standard Short-Term Average / Long-Term Average (STA/LTA) algorithm. The implementation utilizes a custom, memory-efficient `RingBuffer` template class in C++ to maintain rolling sums, allowing $O(1)$ average calculations.
- *Short-Term Window (STA):* 100 samples (1 second of telemetry), representing the immediate seismic transient.
- *Long-Term Window (LTA):* 1000 samples (10 seconds of telemetry), representing the background noise floor.
- *Trigger Condition:* An earthquake is registered when the STA/LTA ratio exceeds `1.8f`, provided the STA absolute value is also above the noise floor.

== FreeRTOS Task Architecture

The firmware utilizes FreeRTOS to decouple time-critical sensor acquisition from network latency.
- *`sensorTask`:* Pinned to a high priority, it wakes exactly every 10ms to poll the ADXL345 and execute the DSP pipeline. Upon detecting a seismic event, it pushes a `SeismicEvent` struct to the `eventQueue`.
- *`networkTask`:* Operates asynchronously at a lower priority. It consumes the `eventQueue`, synchronizes the event timestamp via NTP (`pool.ntp.org`), signs the payload, and dispatches the MQTT message. This design ensures that network blocking or Wi-Fi reconnects never halt the continuous monitoring of the accelerometer.
- *`gnssTask` (optional):* When the GNSS subsystem is compiled in, a dedicated task (priority 2) continuously feeds NMEA frames into the parser so the coordinate pipeline is always live.

== Zero-Trust Serial Fallback 

The edge node tolerates complete MQTT/WiFi loss without losing cryptographically-attested telemetry. The `networkTask` becomes a *first-available-path* dispatcher: `MQTT → USB CDC Serial → Retention Ring`.

- *Framing:* `SerialFallback.h` builds `[QG:FB]{...}` frames whose JSON is *byte-identical* to the MQTT payload (`value`, `sensor_id`, `device_timestamp`, `signature_hex`). The marker lets the host bridge filter CDC noise without parsing every line.
- *Host-aware routing:* `Serial.isConnected()` (HWCDC, `ARDUINO_USB_CDC_ON_BOOT=1`) distinguishes a real USB host from a power-only charger; with no host the event is retained rather than written to a dead port. The pure routing function `decidePath(mqttReachable, usbHostPresent, timeValid)` is shared between the firmware and the host SIL test suite.
- *Retention & drain:* A bounded `RetentionRing<100>` holds events in FIFO order (oldest overwritten on overflow). When a path becomes reachable the ring is drained in order; each retained event is *re-signed* with the current wall time at drain so the backend ±300 s anti-replay window accepts the retransmission.
- *Offline wall clock:* NTP is opportunistic (`pool.ntp.org` via `configTime`). At the first successful sync the firmware anchors `epochAtSync + millis()`; subsequent timestamps remain valid after WiFi drops and no frame is emitted before `timeValid`.
- *Host bridge:* `firmware/tools/serial_bridge.py` reads `/dev/ttyACM0`, filters `[QG:FB]` lines via `parse_frame()`, validates the ingestion URL against SSRF (`_validate_api_url`), and POSTs to `/readings/` with `X-API-Key` — the same forwarding path as `mqtt_subscriber.py`. A `test_serial_fallback.cpp` suite covers `buildSerialFrame`, `decidePath` and ring semantics on the host.

== Diagnostic LED Indicators

The ESP32-C3 firmware drives two diagnostic LEDs to provide immediate visual feedback of the node's operational state without requiring a serial monitor:
- *Boot Test:* Upon power-up, both the Blue and Red LEDs blink simultaneously twice to verify wiring integrity before the FreeRTOS tasks start.
- *Solid Blue:* The node is fully online, with both Wi-Fi connected and an active MQTT session established with the broker.
- *Single-Blinking Blue:* Wi-Fi is connected, but the MQTT broker is unreachable. The node is attempting opportunistic reconnection.
- *Double-Blinking Blue:* Wi-Fi connection is lost. The node is actively scanning and attempting to re-associate with the AP.
- *Solid Red (3-second pulse):* A seismic event (earthquake) was successfully detected by the STA/LTA algorithm. This overrides any blue LED state.
- *Serial Fallback Indication:* If a seismic event occurs while the Blue LED is blinking (no MQTT), the Red LED will still pulse. This specific combination (Blinking Blue + Solid Red pulse) visually confirms to the operator that the node has fallen back to writing the cryptographically-signed event to the USB CDC Serial port or parking it in the Retention Ring.

== PCB Design & Physical Assembly (v2.0.0)

With the v2.0.0 milestone, the QuakeGuard hardware has matured from a breadboard prototype to a custom Printed Circuit Board (PCB), designed in KiCad. The `hardware/` directory contains the complete schematic, PCB layout, and manufacturing Gerber files.
- *Layout Integration:* The PCB provides dedicated footprints for the ESP32-C3 SuperMini (designed with footprint headroom to support a future ESP32-S3 variant for edge AI), the ADXL345 accelerometer (powered correctly at 3.3V), and the optional u-blox GNSS receiver.
- *Signal Integrity:* The I2C lines (SDA on GPIO 7, SCL on GPIO 8) include proper hardware pull-up resistors on the PCB to guarantee stable communication at 100Hz without relying on the weak internal MCU pull-ups.
- *External Interfacing:* A J4 header exposes the GNSS UART lines (RX GPIO 5, TX GPIO 4, PPS GPIO 2) and power rails, allowing modular connection of the GPS antenna for accurate time synchronization and epicentral triangulation.
- *Bill of Materials (BOM):* The exact hardware components required to assemble the QuakeGuard PCB (including the ESP32-C3, ADXL345, optional GNSS, and THT passives) are exported from KiCad and documented in the official project Wiki under the `Bill of Materials` page (see @fig-pcb).

#figure(
  image("assets/pcb_assembled.jpg", width: 90%),
  caption: [
    _The QuakeGuard v2.0.0 fully assembled PCB, featuring the ESP32-C3 SuperMini, the ADXL345 
    accelerometer, and the u-blox GNSS module soldered into their dedicated footprints._
  ],
  numbering: _ => "3",
  placement: auto
) <fig-pcb>

== GNSS Subsystem & NTP Discipline (v1.3.0)

The firmware features an optional GNSS module: an optional module parses NMEA data from a u-blox / NEO-6M / NEO-M8N receiver over the secondary UART (RX GPIO 5, TX GPIO 4, 9600 baud on the JLCPCB — `J4-3→GPIO5`, `J4-4→GPIO4`, `J4-5→GPIO2 PPS` for v2.0.0) at 9600 baud. The module is compiled #strong[only] when `GNSS_ENABLED=1` is present in `esp32_config.env`, so the default build stays hermetic and pulls no `TinyGPSPlus` dependency. Defaults in `GnssModule.h` are `RX 5 / TX 4` to match the fabricated PCB; they remain overridable via `GPS_SERIAL_RX_PIN`/`TX_PIN` in `esp32_config.env` through `extra_script.py`.

- *Last-Known Fix Persistence:* Every reliable fix is saved into NVS (namespace `quake-gnss`, at most once per 60 seconds to limit flash wear). Provisioning therefore reports real coordinates even before the first fix after a cold boot.
- *Staleness Handling:* A live fix older than 10 seconds is treated as stale and the firmware falls back to the last-known value.
- *Provisioning Integration:* During `/devices/register`, the node reports the live GNSS fix when available, else the last-known-from-NVS fix; when neither exists it uses `GNSS_FALLBACK_LAT`/`LON` from `esp32_config.env` if defined (indoor testing), otherwise coordinates are omitted so the backend can assign the zone once placed.
- *NTP + PPS Discipline:* The core feature of v1.3.0. The pulse-per-second (PPS) hardware interrupt (GPIO 2) records the precise `millis()` at the start of each UTC second. The `networkTask` synchronizes via NTP and then disciplines the internal `epochAtSync` directly to the last PPS interrupt, ensuring stratum-1-like millisecond precision for all seismic telemetry.

== Software-in-the-Loop (SIL) Validation

To ensure the theoretical STA/LTA model translates correctly to the real world, the QuakeGuard firmware edge core (`DetectionCore.h`) is tested headlessly against a Python-based Software-in-the-Loop pipeline.
- *Open Data Integration:* The pipeline dynamically queries the public INGV FDSN web service via ObsPy, fetching raw waveforms from the `IV` and `MN` open networks for specific historical baselines (e.g., L'Aquila 2009, Amatrice 2016, Emilia 2012).
- *DSP Simulation:* Raw data is deconvolved to physical acceleration ($m/s^2$), causal bandpass-filtered (1-20 Hz), and resampled to exactly 100 Hz to simulate the ADXL345 physical output.
- *Algorithmic Certification:* The multidimensional calibration sweep proves the current STA/LTA threshold (`ratio=2.4`, `floor=0.02G`) yields a theoretical 80% True Positive Rate with a 0.0% False Alarm Rate against the validation dataset, demonstrating maximal rejection of distant micro-seismicity (like Salizzole at 100km) while triggering on near-fault impulses within 3 seconds of the P-wave arrival. (Note: The firmware deployed on edge nodes uses a more sensitive operational threshold of `1.8f` to ensure no P-waves are missed in the field, whereas the stricter ratio of `2.4` is used specifically in the offline SIL calibration to certify a theoretical 0% False Alarm Rate bound, as shown in @fig-roc.)

#figure(
  image("assets/roc.png", width: 80%),
  caption: [
    _Receiver Operating Characteristic (ROC) curve of the edge STA/LTA algorithm.
    This represents a theoretical, preliminary MVP validation based on 5 historical 
    events. The curve reaches a hard upper bound at 0.8 (80%) True Positive Rate (Sensitivity).
    This limit represents a highly desirable geophysical outcome: 4 out of 5 historical 
    events are perfectly identified without any false alarms (FAR = 0.0), while the 5th 
    event (a weak micro-seismicity recorded at >100km distance) correctly fails to 
    trigger the algorithm, proving the firmware's robustness against distant noise._
  ],
  numbering: _ => "4",
  placement: auto
) <fig-roc>