= Cryptographic Security & Provisioning

QuakeGuard implements a Zero-Trust security model for its IoT edge nodes. To prevent rogue devices from injecting false seismic data (spoofing) or re-transmitting old events (replay attacks), the system relies on asymmetric cryptography and strict temporal validation.

== Cryptographic Identity (ECDSA)

Upon its first boot, the ESP32-C3 utilizes the `mbedtls` library to generate a unique Elliptic Curve Digital Signature Algorithm (ECDSA) key pair using the NIST P-256 curve (`secp256r1`). 
- *Private Key:* Stored securely and permanently in the device's Non-Volatile Storage (NVS). It never leaves the device and is used exclusively to sign outgoing telemetry.
- *Public Key:* Extracted in DER format, converted to a hexadecimal string, and acts as the unforgeable cryptographic identity of the sensor within the backend database.

== Captive Portal Onboarding

To seamlessly connect the hardware identity with the user's mobile app, the ESP32 hosts an embedded HTTP Captive Portal during its first boot. Users connecting to the `QuakeGuard-Setup` network are immediately presented with a custom HTML page containing two crucial elements:
- A direct download link for the QuakeGuard Mobile App (APK), dynamically resolving to the latest GitHub release.
- The sensor's hexadecimal ECDSA Public Key, generated by `mbedtls` and displayed in clear text.

This allows the user to easily copy the hardware's cryptographic identity and paste it directly into the mobile app's enrollment flow, eliminating complex manual extractions.

== Automated Provisioning Handshake

Before transmitting any seismic data, an unregistered sensor must complete an automated handshake with the Control Plane (detailed in @fig-provisioning-a and @fig-provisioning-b):
+ The device sends a POST request to the `/devices/register` endpoint, providing its generated `public_key_hex`, MAC address, GPS coordinates, and a hardcoded `ENROLLMENT_TOKEN`.
+ The backend validates the factory enrollment token to ensure the device is authorized to join the network.
+ Using a geohash-based Redis fast-path index with an authoritative PostGIS fallback (`ST_Contains`), the backend spatially evaluates the provided GPS coordinates against the predefined zones and assigns the sensor to the smallest containing geographic polygon. When a GNSS module is attached, the coordinates are the live fix (or the last-known fix persisted in NVS); otherwise the node reports a hardcoded placeholder until provisioned in place.
+ A unique `sensor_id` is returned to the device, which saves it to NVS for all future communications.

#figure(
  image("assets/fig05_1-provisioning-handshake-sequence.pdf", width: 96%),
  caption: [_Provisioning Handshake Sequence_],
  numbering: _ => "5.1",
  placement: top
) <fig-provisioning-a>

#figure(
  image("assets/fig05_2-provisioning-handshake-sequence.pdf", width: 94%),
  caption: [_Provisioning Handshake Sequence (continuation)_],
  numbering: _ => "5.2",
  placement: top
) <fig-provisioning-b>

== Payload Authentication & Integrity

When a seismic event triggers the DSP pipeline, the firmware constructs a string containing the measured magnitude and the current timestamp (format: `value:timestamp`). Under normal operation the timestamp is the NTP-synchronized wall time; when the serial fallback drains the retention ring it is the software wall clock `epochAtSync + millis()` at drain time, and the payload is *re-signed* with the current time so the backend's replay window accepts it. This string is hashed via SHA-256 and signed with the device's private key. 

The resulting JSON payload includes the data, the timestamp, and the `signature_hex` — identical on the MQTT and serial data planes (`[QG:FB]` frames carry the same JSON behind the marker). Once received by the backend, the `validate_iot_payload` dependency pipeline enforces four security gates:
- *API Key Verification:* Validates the `X-API-Key` header using a constant-time comparison (`hmac.compare_digest`) to prevent timing attacks.
- *Sensor Status:* Confirms the sensor ID exists and is marked as `active` in the PostgreSQL database.
- *Anti-Replay Protection:* Compares the device's timestamp against the server's UTC time. Payloads older than a 300-second threshold are outright rejected with a `403 Forbidden` error.
- *Signature Verification:* The backend utilizes the Python `cryptography` library to verify the ECDSA signature against the public key associated with that sensor. The implementation robustly supports both DER-encoded signatures (native to MbedTLS) and raw concatenated $r || s$ signatures.