"""
Pydantic Schemas (Data Transfer Objects)
----------------------------------------
Defines request/response structures for API communication.
Includes validation fields for security signatures and model serialization.
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional, List
from datetime import datetime

# ==========================================
# ZONE SCHEMAS
# ==========================================
class ZoneBase(BaseModel):
    city: str

class ZoneCreate(ZoneBase):
    pass

class ZoneUpdate(BaseModel):
    city: Optional[str] = None

class Zone(ZoneBase):
    id: int
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# SENSOR SCHEMAS
# ==========================================
class SensorBase(BaseModel):
    active: bool
    zone_id: Optional[int] = None

class SensorCreate(SensorBase):
    """
    Payload for creating a new sensor.
    Includes GPS and Security credentials.
    """
    latitude: float = Field(..., ge=-90, le=90, description="GPS Latitude")
    longitude: float = Field(..., ge=-180, le=180, description="GPS Longitude")
    # The Public Key generated by the ESP32 (Hex string)
    public_key_hex: str = Field(..., description="ECDSA Public Key (NIST256p) in Hex format")

class SensorUpdate(BaseModel):
    active: Optional[bool] = None
    zone_id: Optional[int] = None
    public_key_hex: Optional[str] = Field(default=None, min_length=64)

class Sensor(SensorBase):
    id: int
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    last_fix_at: Optional[datetime] = None
    # We do not return the public key by default to keep responses clean,
    # but it can be added if needed.
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# READING (DATA POINT) SCHEMAS
# ==========================================
class ReadingCreate(BaseModel):
    """
    Payload for data ingestion.
    MUST include signature and device timestamp for verification.
    """
    value: int = Field(
        ..., 
        ge=-8192, 
        le=8192, 
        description="Vibration value. Must be within the physical constraints of the ADXL345 sensor to prevent spoofing."
    )
    sensor_id: int = Field(..., gt=0, description="The ID of the registered sensor")
    device_timestamp: int = Field(..., gt=1600000000, description="Unix timestamp of the event")
    device_timestamp_ms: Optional[int] = Field(default=None, description="Exact UTC millisecond timestamp for latency calculation")
    signature_hex: str = Field(..., min_length=128, description="ECDSA NIST256p Signature")

    # System Telemetry (v2.1.0 Grafana Observability)
    free_heap: Optional[int] = None
    rssi: Optional[int] = None
    gnss_satellites: Optional[int] = None

class Reading(BaseModel):
    id: int
    value: int
    sensor_id: int
    recorded_at: datetime
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    
    # System Telemetry
    latency_ms: Optional[int] = None
    free_heap: Optional[int] = None
    rssi: Optional[int] = None
    gnss_satellites: Optional[int] = None

    model_config = ConfigDict(from_attributes=True)

# ==========================================
# DEVICE REGISTRATION SCHEMAS
# ==========================================
class DeviceRegisterRequest(BaseModel):
    """Payload sent by the ESP32 during its first boot."""
    public_key_hex: str = Field(..., description="The generated ECDSA public key")
    mac_address: str = Field(..., max_length=17, description="The hardware MAC address")
    enrollment_token: str = Field(..., description="The hardcoded factory enrollment token")
    latitude: float = Field(default=None, ge=-90, le=90)
    longitude: float = Field(default=None, ge=-180, le=180)

# ==========================================
# ALERT SCHEMAS
# ==========================================
class Alert(BaseModel):
    id: int
    zone_id: int
    magnitude: float
    message: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

# ==========================================
# EMERGENCY REPORT SCHEMAS (AI / Ollama)
# ==========================================
class EmergencyReport(BaseModel):
    """AI-generated emergency report attached to a confirmed Alert."""
    id: int
    alert_id: int
    zone_id: int
    magnitude: float
    status: str
    summary: Optional[str] = None
    recommendations: Optional[str] = None
    model_used: Optional[str] = None
    error: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)

# ==========================================
# DEMO SCHEMAS
# ==========================================
class DemoAlertRequest(BaseModel):
    """Payload for manually triggering a simulated earthquake alert."""
    zone_id: int = Field(default=1, description="Target Zone ID for the alert")
    magnitude: float = Field(default=7.5, le=10.0, description="Simulated earthquake magnitude")
    message: str = Field(default="Simulated Critical Event", description="Custom alert message")